### PR TITLE
Updated Main.vue

### PR DESCRIPTION
**Pull request by ackushiw**
Hi Alex,

I've made some edits to your Main.vue
Your Bootstrap import was working fine. You just needed to wrap `<b-tab>` in `<b-tabs>`

I also refactored your component a bit. I put your template code in the Main.vue. I find it helpful to see the template while working on the component script. You might want to do that with the CSS as well... you can add a `scoped` attribute to your `<style>` that way the CSS is isolated to the component. 

If you prefer to keep the HTML separate I can change it back. 

Vue was also giving a warning about mutating your props, so I refactored it to be implemented in the component `data()` to improve this further you might want to look at using Vuex. 

Lastly, I'm toggling `<b-modal>` using `v-model`, `v-if` only adds it to the template, it doesn't control the show/hide state of the b-modal. 

Let me know if you have any other questions.

-Alexander

### CODE REVIEW

**Comment by spearheadOne** [comment]
Hi Alexander,
Thanks a lot for the changes. Just a quick question: did you set up style-load for webpack and if yes how did you do it?

-Alex

**Comment by ackushiw** [comment]
Hi, 

I only changed the Main.vue didn't touch webpack or the rest of the setup. You'd set up everything correctly, just weren't quite implementing the https://bootstrap-vue.js.org components correctly.

If you're looking at using Vue with Server Side Rendering I can suggest looking at Nuxt... it's pretty awesome. https://nuxtjs.org/ 

-Alexander

**Comment by spearheadOne** [comment]
Ok. Actually I found the root cause:

1) Separate plugins in Vue.use
2) Import should be like this: import '../node_modules/bootstrap/dist/css/bootstrap.css'

**Comment by ackushiw** [comment]
Usually node_modules aren't referenced with a relative path, makes things easier if you change file structure. 
You might want to have a look at this template to see how they use bootstrap in a Vue project https://github.com/bootstrap-vue/webpack/tree/develop/template/src

**Pull request merged**
